// Code generated by go generate using nativeyaml.tmpl; DO NOT EDIT native_yaml_shadow.go.
package openapi3

import (
	yaml "go.yaml.in/yaml/v3"
)

// UnmarshalYAML for the types whose YAML form is a mapping of declared fields
// plus extensions.
//
// The local shadow type is what stops the decoder recursing into this method;
// converting the receiver to it decodes in place, so only the two fields the
// decoder skips are set afterwards. Everything else is in decodeMapping.

// UnmarshalYAML sets Components from node.
func (components *Components) UnmarshalYAML(node *yaml.Node) error {
	type bis Components
	ext, err := decodeMapping(node, (*bis)(components))
	if err != nil {
		return err
	}
	components.Extensions, components.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, components, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Contact from node.
func (contact *Contact) UnmarshalYAML(node *yaml.Node) error {
	type bis Contact
	ext, err := decodeMapping(node, (*bis)(contact))
	if err != nil {
		return err
	}
	contact.Extensions, contact.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, contact, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Discriminator from node.
func (discriminator *Discriminator) UnmarshalYAML(node *yaml.Node) error {
	type bis Discriminator
	ext, err := decodeMapping(node, (*bis)(discriminator))
	if err != nil {
		return err
	}
	discriminator.Extensions, discriminator.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, discriminator, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Encoding from node.
func (encoding *Encoding) UnmarshalYAML(node *yaml.Node) error {
	type bis Encoding
	ext, err := decodeMapping(node, (*bis)(encoding))
	if err != nil {
		return err
	}
	encoding.Extensions, encoding.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, encoding, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Example from node.
func (example *Example) UnmarshalYAML(node *yaml.Node) error {
	type bis Example
	ext, err := decodeMapping(node, (*bis)(example))
	if err != nil {
		return err
	}
	example.Extensions, example.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, example, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets ExternalDocs from node.
func (e *ExternalDocs) UnmarshalYAML(node *yaml.Node) error {
	type bis ExternalDocs
	ext, err := decodeMapping(node, (*bis)(e))
	if err != nil {
		return err
	}
	e.Extensions, e.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, e, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Info from node.
func (info *Info) UnmarshalYAML(node *yaml.Node) error {
	type bis Info
	ext, err := decodeMapping(node, (*bis)(info))
	if err != nil {
		return err
	}
	info.Extensions, info.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, info, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets License from node.
func (license *License) UnmarshalYAML(node *yaml.Node) error {
	type bis License
	ext, err := decodeMapping(node, (*bis)(license))
	if err != nil {
		return err
	}
	license.Extensions, license.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, license, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Link from node.
func (link *Link) UnmarshalYAML(node *yaml.Node) error {
	type bis Link
	ext, err := decodeMapping(node, (*bis)(link))
	if err != nil {
		return err
	}
	link.Extensions, link.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, link, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets MediaType from node.
func (mediaType *MediaType) UnmarshalYAML(node *yaml.Node) error {
	type bis MediaType
	ext, err := decodeMapping(node, (*bis)(mediaType))
	if err != nil {
		return err
	}
	mediaType.Extensions, mediaType.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, mediaType, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets OAuthFlow from node.
func (flow *OAuthFlow) UnmarshalYAML(node *yaml.Node) error {
	type bis OAuthFlow
	ext, err := decodeMapping(node, (*bis)(flow))
	if err != nil {
		return err
	}
	flow.Extensions, flow.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, flow, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets OAuthFlows from node.
func (flows *OAuthFlows) UnmarshalYAML(node *yaml.Node) error {
	type bis OAuthFlows
	ext, err := decodeMapping(node, (*bis)(flows))
	if err != nil {
		return err
	}
	flows.Extensions, flows.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, flows, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Parameter from node.
func (parameter *Parameter) UnmarshalYAML(node *yaml.Node) error {
	type bis Parameter
	ext, err := decodeMapping(node, (*bis)(parameter))
	if err != nil {
		return err
	}
	parameter.Extensions, parameter.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, parameter, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets PathItem from node.
func (pathItem *PathItem) UnmarshalYAML(node *yaml.Node) error {
	type bis PathItem
	ext, err := decodeMapping(node, (*bis)(pathItem))
	if err != nil {
		return err
	}
	pathItem.Extensions, pathItem.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, pathItem, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets RequestBody from node.
func (requestBody *RequestBody) UnmarshalYAML(node *yaml.Node) error {
	type bis RequestBody
	ext, err := decodeMapping(node, (*bis)(requestBody))
	if err != nil {
		return err
	}
	requestBody.Extensions, requestBody.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, requestBody, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Response from node.
func (response *Response) UnmarshalYAML(node *yaml.Node) error {
	type bis Response
	ext, err := decodeMapping(node, (*bis)(response))
	if err != nil {
		return err
	}
	response.Extensions, response.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, response, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets SecurityScheme from node.
func (ss *SecurityScheme) UnmarshalYAML(node *yaml.Node) error {
	type bis SecurityScheme
	ext, err := decodeMapping(node, (*bis)(ss))
	if err != nil {
		return err
	}
	ss.Extensions, ss.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, ss, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Server from node.
func (server *Server) UnmarshalYAML(node *yaml.Node) error {
	type bis Server
	ext, err := decodeMapping(node, (*bis)(server))
	if err != nil {
		return err
	}
	server.Extensions, server.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, server, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets ServerVariable from node.
func (serverVariable *ServerVariable) UnmarshalYAML(node *yaml.Node) error {
	type bis ServerVariable
	ext, err := decodeMapping(node, (*bis)(serverVariable))
	if err != nil {
		return err
	}
	serverVariable.Extensions, serverVariable.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, serverVariable, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets Tag from node.
func (t *Tag) UnmarshalYAML(node *yaml.Node) error {
	type bis Tag
	ext, err := decodeMapping(node, (*bis)(t))
	if err != nil {
		return err
	}
	t.Extensions, t.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, t, nativeOriginFile())
	return nil
}

// UnmarshalYAML sets XML from node.
func (xml *XML) UnmarshalYAML(node *yaml.Node) error {
	type bis XML
	ext, err := decodeMapping(node, (*bis)(xml))
	if err != nil {
		return err
	}
	xml.Extensions, xml.Origin = ext, originFromNode(node, nativeOriginFile())
	setChildOriginKeys(node, xml, nativeOriginFile())
	return nil
}
